# -*- encoding: utf-8 -*-
require File.expand_path("../lib/version", __FILE__)

Gem::Specification.new do |s|
  s.name        = "<%= $project_name %>"
  s.version     = <%= $module_name %>::VERSION
  s.license     = 'GPL-2'
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['<%= $author_name %>']
  s.email       = ['<%= $author_email %>']
  s.homepage    = "http://<%= $project_name %>.example.com"
  s.summary     = "Command line tool template"
  s.description = "<%= $display_name %> is a command line whose initial skeleton was generated by rubycligen."

  s.required_rubygems_version = ">= 1.3.6"
  s.rubyforge_project         = "<%= $project_name %>"

  s.add_dependency "thor", ">=0.14.0"

  s.files        = `git ls-files`.split("\n")
  s.executables  = `git ls-files`.split("\n").map{|f| f =~ /^bin\/(.*)/ ? $1 : nil}.compact
  s.require_path = 'lib'
end
